version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  springboot:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
